version: "3.8"

services:
  postgres:
    container_name: jaml-auctions-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: jaml-auctions
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
